### ISSUE TITLE
Rename RC3 as 1.0 in github

### ISSUE THREAD

**Issue by dneufeldcu** [cires-ncei/onestop#106]
Update release page and artifacts to reflect 1.0 release.

**Comment by ajakz** [comment]
I removed the "pre-release" tag (so it's not saying it isn't production ready) and changed the title to just v1.0.0 instead of v1.0.0-RC3. I tried to change the tag as well but doing so creates a new tag from the current point that master is at, and it wouldn't let me pick the original commit associated with the v1.0.0-RC3 tag (not recent enough).

I'll wait until touching base with everyone to update more since I may be missing some details on this.
