### ISSUE TITLE
Library updates

### ISSUE THREAD

**Issue by dneufeldcu** [cires-ncei/onestop#35]
See: https://docs.google.com/document/d/1QsZVQYOVvGe8rhSetPMWLfpjyNHo7dXdPnjtWsARCQ4/edit

AC:
- [x] Add gradle plugin for OWASP and add to check task

**Comment by mcquinne** [comment]
So it turns out that several of our dependencies are at the latest version (now) and also have vulnerabilities associated with them:

| Dependency | Version | Vulnerabilities |
| -------------| -------- |----------------|
| groovy          | 2.4.8      | [CVE-2016-6497](http://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2016-6497) |
| spring-cloud-context | 1.1.7.RELEASE | [CVE-2016-9878](http://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2016-9878)
| tomcat          | 8.5.11    | [CVE-2016-6325](http://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2016-6325), [CVE-2016-5425](http://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2016-5425)

So, question for @cires-ncei/onestop team: What do we do next? Do we need to make exceptions for these libraries? Do we search for an older version that does not have the vulnerability associated with it? Should we ask the NC security folks what they need us to do? (And also how do they intend to deploy anything written in groovy...?)

**Comment by mcquinne** [comment]
Also, for devs:

It's probably worth taking a minute to glance over the [testing changes](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-1.4-Release-Notes#test-improvements) that were introduced in spring boot 1.4 (we're at 1.5 now). Nothing huge, but some nice simplifications, and perhaps some optimizations we may want to put in place to speed our tests up. Anyway, just an FYI.

**Comment by mcquinne** [comment]
Going to close this since 0.1.0-RC8 passed the security scan.
