### ISSUE TITLE
View query filter terms

### ISSUE THREAD

**Issue by dneufeldcu** [cires-ncei/onestop#36]
The currently applied query filter terms should be visible as text along top matching search criteria.

AC:

- [ ] Filter text is visible

**Comment by aaronjcaldwell** [comment]
The implementation for this task supplies filter (facet) badges at the top of the collections view which are added when facet criteria are selected and can be removed either directly via a close/remove button on the badge or by unchecking the corresponding facet on the side menu.  Overall, it looks very nice and appears to function consistently.

There were a couple of things worth highlighting but likely beyond the scope of this task. Implementation of filter badges brings attention to the potential desirability to have all search criteria elucidated either with badges or some other means. For example, it might be useful to clearly see the date and geography criteria used to conduct the search.  The site currently follows a pattern used by other similar sites where searches conducted from the header are treated as new searches whereas modifications of criteria on the side menu are treated as drill-down within an existing search. It's likely that users will want to tweak dates, spatial criteria and possible search terms in much the same way they select facets however that functionality doesn't yet exist in the application architecture and therefore isn't easily representable via badges.

It was also noted that badges are currently populated on the interface in the same order they are stored for search submission which is a limitation of the current shape of the store. This becomes apparent when you select facets from one category, then from a different category, then select more from the first category. The badges will reflect the order of the store rather than the user's selection order. Other sites appear to either preserve the user's selection order in the url, even if redundantly (i.e.- "science: oceans, platform: DEM, science: land...") and/or they list their badges/terms in the side menu directly under their respective categories.

We can certainly generate stories out of this with the consideration that much of this may be tackled as the project moves towards time/spatial views.
