### ISSUE TITLE
Break api into microservices

### ISSUE THREAD

**Issue by mcquinne** [cires-ncei/onestop#47]
Break out existing functionality into services:
- Metadata: For metadata loading and management, read/write on staging index
- Search: For fast, scalable reading, readonly on search index
- ETL + Admin: For processing and indexing metadata, read/write on staging and search indices

Note: Think about trade off of building our own layer to serve as a unified api vs having ops build proxies to the various apps.

**Comment by ajakz** [comment]
The services are separated and all tests are successful when run locally, but they keep failing on Travis builds. There's still a little work to get all the tests using http requests instead of dependencies across modules. @mcquinne and I talked yesterday about modifying the API services so they are less interdependent, but agreed that is better done as a different user story. Once I finish getting the tests fully using http, I'd like to consider this as closed regardless of whether the builds are failing, since debugging that has become a huge rabbit hole that might be resolved anyway once the microservices are refactored.

**Comment by dneufeldcu** [comment]
Superseded by #83
