### ISSUE TITLE
Update background image

### ISSUE THREAD

**Issue by dneufeldcu** [cires-ncei/onestop#63]
AC: Use this image (from GOES-R) darken if needed

http://farm1.staticflickr.com/681/32440453126_c30250ddc2_b.jpg

**Comment by mcquinne** [comment]
I'm confused by this choice for three reasons:
1. I thought we decided this morning that if we really wanted to change the background then we should wait for web team input
2. This image is going to have the exact same issues as the current one with regard to lack of contrast with white text
3. It has logos in the corner and one is NASA which doesn't make sense on our page... I guess we need to edit them out?

I still say we should just leave our background as it is because changing it was not listed as a requirement in the first web team review. I think we should cut a release and start it through the process so that we can get a second review and see if it's really a problem or not.

If we really do want to change it, then I would prefer to put the decision on the web team since it's likely that whatever we choose will just get shot down anyway.

**Comment by mcquinne** [comment]
Disregard my previous comment. Turns out there was a conversation when I wasn't around explaining that this image *IS* the recommendation of the web team.

Still not sure I understand how it will be better... but that doesn't matter!
