### ISSUE TITLE
Fix sure check

### ISSUE THREAD

**Issue by dneufeldcu** [cires-ncei/onestop#69]
Admin metadata recreate option checks for sure parameter but not the conditional.

**Comment by ajakz** [comment]
Noting here, because I'm not sure how we should handle this: true values (true, yes, 1) run this as expected, false values (false, no, 0) don't do anything, anything else throws an error (since it's not a boolean). Should we change this in any way? Makes sense that non-boolean values are uninterpretable and thus erroneous, but do we really want to return nothing for false values?

Also, might be nice to write a test or two for these (and other) endpoints...
