### ISSUE TITLE
Investigate contribution strategies

### ISSUE THREAD

**Issue by dneufeldcu** [cires-ncei/onestop#87]
Select 2-3 open source projects. 

Review their contribution strategies and present options to team.  Need to discuss epics in this context.

**Comment by aaronjcaldwell** [comment]
Leveraged 18F's write-ups for release and contribution as templates for our own since their approach is in many ways roughly in-line with discussions we've had internally. There were still several aspects to tweak as some of our internal processes and build practices are pretty different. Related to this, we'll want to talk about whether or not we should use Code Climate for code coverage analysis. It's free for Open Source projects. I've tested it on ours and gotten useful results. Nevertheless, there are a multitude of ways to approach this so we can discuss. The branch and initial commit are intended as a conversation starter around contribution strategies. We should consider how we ultimately want to proceed (and potentially restructure our git code) before issuing a pull request and merging back to master.

**Comment by aaronjcaldwell** [comment]
Build processes are only lightly covered but should definitely be fleshed out more. We could also rethink which content is currently in the readme and reallocate as needed

**Comment by ajakz** [comment]
The work done by Aaron was incorporated into the [wiki](https://github.com/cires-ncei/onestop/wiki); we can close the branch once we're satisfied with our documentation. There were some things referenced but not written out, like templates for pull requests and issues, that I left in place. Not sure if we really want to have those or not.

I also moved the info in the readme file to a few pages in the wiki but didn't delete the readme as I wasn't sure if we wanted to do that (the wiki is not part of the code like the readme is).

We need to review the internal development practices page as a team, see if it meets the needs identified at our last retro, as it is the primary resolution of this issue.
